const apiSdkRegistry: any = {
  'registration-api': { method: 'customer_signup', entity: 'registration' },
  'guest-login-api': { method: 'existing_user_signin', entity: 'signin' },
  'otp-login-api': { method: 'signin', entity: 'signin' },
  'google-login-api': { method: 'signin', entity: 'signin' },
  'login-api': { method: 'get_access_token', entity: 'access_token' },
  'default-currency-api': { method: 'get_default_currency', entity: 'product' },
  'multi-language-data-api': { method: 'get_languages', entity: 'translation' },
  'navbar-api': { version: 'v2', method: 'get_mega_menu', entity: 'mega_menu' },
  'banner-api': { method: 'get', entity: 'banner' },
  'display-tags-api': { method: 'get_tagged_products', entity: 'product' },
  'breadcrums-api': { method: 'breadcrums', entity: 'mega_menu' },
  'get-product-listing-filters-api': { method: 'get_filters', entity: 'filter' },
  'product-list-api': { method: 'get_list', entity: 'product' },
  'catalog-product-list-api': { method: 'get_items', entity: 'catalog' },
  'brand-product-list-api': { method: 'get_list', entity: 'product' },
  'product-detail-api': { method: 'get_details', entity: 'product' },
  'product-variants-api': { method: 'get_variants', entity: 'variant' },
  'product-stock-availability': { method: 'check_availability', entity: 'product' },
  'product-matching-items': { method: 'get_recommendation', entity: 'product' },
  'product-review': { method: 'get_customer_review', entity: 'customer_review' },
  'add-product-review': { method: 'create_customer_review', entity: 'customer_review' },
  'get-product-specifications': { method: 'get_product_specifications', entity: 'utils' },
  'get-wishlist-items-api': { method: 'get_wishlist_items', entity: 'wishlist' },
  'add-item-to-wishlist-api': { method: 'add_to_wishlist', entity: 'wishlist' },
  'remove-item-from-wishlist-api': { method: 'remove_from_wishlist', entity: 'wishlist' },
  'get-cart-list-items-api': { method: 'get_list', entity: 'cart' },
  'add-cart-api': { method: 'put_products', entity: 'cart' },
  'clear-cart-api': { method: 'clear_cart', entity: 'cart' },
  'remove-single-item-cart-api': { method: 'delete_products', entity: 'cart' },
  'get-user-addresses-api': { method: 'get', entity: 'customer_address' },
  'get-order-summary-api': { method: 'get_summary', entity: 'order' },
  'get-transporters-list-api': { method: 'get_transporters', entity: 'profile' },
  'get-state-list-api': { method: 'get_states', entity: 'utils' },
  'get-cities-list-api': { method: 'get_cities', entity: 'utils' },
  'create-user-address-api': { method: 'put', entity: 'customer_address' },
  'order-list-api': { method: 'get_list', entity: 'order' },
  'order-detail-api': { method: 'get_order_details', entity: 'order' },
  'order-reports-api': { method: 'report_data', entity: 'sales_order_report' },
  'place-order-api': { method: 'place_order', entity: 'order' },
};

export default apiSdkRegistry;
