export const colors = {
  primary: '#fff',
  softWhite: '#f8f9fa',
  red: '#ff3400',
  black: '#000',
  lightgray: '#F5F5F5',
  mediumGray: '#ddd',
  darkGray: '#333',
  white: '#fff',
  transparent: 'transparent',
  lightPink: '#F1E9E9',
  darkPink: '#792E2C',
  darkBlue: '#082468',
  lightBlue: '#E5ECFF',
  grey: '#EDECEC',
  lightPurple: '#F2EEFC',
  cardTextGrey: '#9F9F9F',
  softGray: '#F6F6F6',
};
