export const CONSTANTS = {
  API_BASE_URL: process.env.NEXT_PUBLIC_API_URL,
  API_MANDATE_PARAMS: '/api/method/summitapp.sdk.api',
  SUMMIT_APP_CONFIG: {
    app_name: '/api/method/summitapp.sdk.api',
    version: 'v2',
  },
  ARC_APP_CONFIG: {
    app_name: '/api/method/arcapp.sdk.api',
    version: 'v1',
  },
  SUMMIT_API_SDK: '/api/method/summitapp.sdk.api',
  CUSTOM_API_SDK: '/api/method/arcapp.sdk.api',
  VERSION: 'v2',
  SUMMIT_API_SDK_VERSION: 'v2',
  CUSTOM_API_SDK_VERSION: 'v1',
  ALLOW_GUEST_TO_ACCESS_SITE_EVEN_WITHOUT_AUTHENTICATION: false,
  ENABLE_META_TAGS: false,
  ENABLE_LOGIN_USING_OTP: false,
  ENABLE_LOGIN_USING_GOOGLE_ID: false,
  ENABLE_BULK_ORDER: false,
  ENABLE_APPLY_COUPON_CODE: false,
  ENABLE_STORE_CREDIT: false,
  ENABLE_REDIRECT_FEATURE: false,
  ENABLE_PRODUCT_ENQUIRY_FEATURE: false,
  USE_SINGLE_ENQUIRY: false,
  DOES_PRODUCT_HAS_VARIANTS: false,
  SHOW_MORE_ITEMS: 'paginate',
  ENABLE_MISSING_PARTS: false,
  SHOW_FUTURE_STOCK_AVAILABILITY_TO_GUEST: false,
  SHOW_FUTURE_STOCK_AVAILABILITY: false,
  ADD_TO_CART_FOR_GUEST: false,
  SHOW_TRANSPORTERS_LIST_TO_DEALER: false,
  ALLOW_REQUEST_QUOTATION: false,
  ENABLE_SEARCH_TEXT: false,
  ENABLE_PAYMENT_INTEGRATION: false,
  DEFAULT_CURRENCY_VALUE: 'rupee',
  DEFAULT_LANGUAGE: 'en',
  ENABLE_SHOP_ON_AMAZON: false,
};
